[package]
name = "emesh"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Library for processing 3D polygon meshes."


[dependencies]
emesh-core = { version = "0.0.1-alpha.3", path = "../emesh-core" }

